### ISSUE TITLE
Monthly Sanpshot option for Netapp Volumes

### ISSUE THREAD

**Issue by koushikgongireddy** [GoogleCloudPlatform/terraform-google-netapp-volumes#23]
Hi,

Currently this module only supports daily, hourly and weekly Snapshot option and doesn't support Monthly snapshot.
https://github.com/GoogleCloudPlatform/terraform-google-netapp-volumes/blob/main/main.tf#L57

But its provided and supported by Terraform Registry -https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/netapp_volume#monthly_schedule

Can we please add support for Monthly snapshot option.

Thanks
Koushik

**Comment by okrause** [comment]
@imrannayer FYI. Provider supports monthly, but the TF module not (yet). Can you please have a look?

**Comment by koushikgongireddy** [comment]
@okrause @imrannayer Created PR for the same - https://github.com/GoogleCloudPlatform/terraform-google-netapp-volumes/pull/25
Please check once

**Comment by okrause** [comment]
> @okrause @imrannayer Created PR for the same - #25 Please check once

LGTM

**Comment by imrannayer** [comment]
Fixed in #27
