### ISSUE TITLE
Make Volume creation optional

### ISSUE THREAD

**Issue by koushikgongireddy** [GoogleCloudPlatform/terraform-google-netapp-volumes#24]
Hi,

Good to have below 2 scenarios

1. Currently we can only create 1 volume and 1 pool with this module, is there a way we can create multiple volumes and pools using same module in single project?

2. Currently only Pool creation is conditional and not Volume. Please add volume creation also conditional.

Thanks
Koushik

**Comment by imrannayer** [comment]
@koushikgongireddy 
1) You can create 1 pool and multiple volumes. parameter `storage_volumes` is list of object where each object represent 1 volume. See [example](https://github.com/GoogleCloudPlatform/terraform-google-netapp-volumes/blob/32e140ae8774c8ccb4438b18078503f1f6f52b98/examples/simple_example/main.tf#L98). It is creating two volumes. You can call this module in loop to create multiple pools and volumes.

2) I am assuming you want to use this module to create a pool without any volume. If that's request we can work on it. Let me know if thats what you are looking for.

**Comment by koushikgongireddy** [comment]
@imrannayer Thanks for the details
1. We will leverage this option and use it accordingly.
2. Yeah, that's correct. We need conditional option for both volumes and pools so we can only create them as per needed basis. We don't want both to be created if we want only 1(either volume or pool)

**Comment by imrannayer** [comment]
@koushikgongireddy volume creation is optional in version 1.0+. Can you plz try and leme know if it works for you?

**Comment by koushikgongireddy** [comment]
@imrannayer Can you share an example on how we can test it.
I don't see the conditional set for volumes!

**Comment by imrannayer** [comment]
[Pool only](https://github.com/GoogleCloudPlatform/terraform-google-netapp-volumes/blob/2c0878c15076257fffd9c3c651fe3c493d582b72/examples/simple_example/main.tf#L146)
[Volume Only](https://github.com/GoogleCloudPlatform/terraform-google-netapp-volumes/blob/2c0878c15076257fffd9c3c651fe3c493d582b72/examples/simple_example/main.tf#L178)

**Comment by koushikgongireddy** [comment]
Thanks @imrannayer  Let me check and get back!!
